#!/usr/bin/env node
/**
 * List all theorems, definitions, lemmas, structures, and abbreviations
 * in Lean/EGPT/Complexity/ for audit and inventory purposes.
 *
 * Usage: node scripts/list_complexity_declarations.js
 * Output: Lean/EGPT/Complexity/COMPLEXITY_INVENTORY.md
 */

const { execSync } = require('child_process');
const path = require('path');
const fs = require('fs');

const REPO_ROOT = path.resolve(__dirname, '..');
const COMPLEXITY_DIR = path.join(REPO_ROOT, 'Lean', 'EGPT', 'Complexity');
const OUTPUT_FILE = path.join(COMPLEXITY_DIR, 'COMPLEXITY_INVENTORY.md');

// Match declaration start and extract name (first identifier, optionally dotted).
// Handles optional leading modifiers: noncomputable, @[simp], etc.
const DECL_RE = /^\s*(?:noncomputable\s+)?(?:@\[[^\]]+\]\s+)*(theorem|def|lemma|structure|abbrev)\s+(\w+(?:\.\w+)?)/;

function extractDeclarations(filePath) {
  const content = fs.readFileSync(filePath, 'utf-8');
  const lines = content.split('\n');
  const decls = [];
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const match = line.match(DECL_RE);
    if (match) {
      const kind = match[1].trim();
      const name = match[2];
      decls.push({ name, kind, line: i + 1 });
    }
  }
  return decls;
}

function main() {
  const files = fs.readdirSync(COMPLEXITY_DIR)
    .filter(f => f.endsWith('.lean'))
    .sort();

  const allDecls = [];
  for (const file of files) {
    const filePath = path.join(COMPLEXITY_DIR, file);
    const decls = extractDeclarations(filePath);
    for (const d of decls) {
      allDecls.push({ ...d, file });
    }
  }

  const lines = [];
  lines.push('# Complexity Folder — Declaration Inventory');
  lines.push('');
  lines.push('> Generated by `node scripts/list_complexity_declarations.js`');
  lines.push('');
  lines.push('| Declaration | File | Type | Line |');
  lines.push('|-------------|------|------|------|');

  for (const d of allDecls) {
    const kind = d.kind === 'def ' ? 'def' : d.kind;
    lines.push(`| \`${d.name}\` | ${d.file} | ${kind} | ${d.line} |`);
  }

  lines.push('');
  lines.push(`**Total: ${allDecls.length} declarations** across ${files.length} .lean files.`);
  lines.push('');

  fs.writeFileSync(OUTPUT_FILE, lines.join('\n'), 'utf-8');
  console.log(`Wrote ${path.relative(REPO_ROOT, OUTPUT_FILE)} (${allDecls.length} declarations)`);
}

main();
