import EGPT.Core
import EGPT.Complexity.Core
import EGPT.NumberTheory.Core
import EGPT.Entropy.Common

open EGPT EGPT.Complexity EGPT.NumberTheory.Core EGPT.Constraints
open EGPT.Entropy.Common

namespace EGPT.Complexity.UTM

/-!
# The EGPT Computation Model: Sequential Tape Reading

## Why Memory Access Is Not Free

The standard RAM model assumes O(1) memory access: reading any cell costs one
step regardless of its position. This is a cost-accounting abstraction that does
not hold in physical reality. To access bit n on a tape, a read head must
traverse n positions. The standard model hides this traversal cost.

The standard Turing Machine model charges for head movement (one step per cell),
but still allows the machine to revisit cells and loop — so a tape of length L
can drive 2^L or more steps of computation, because the TM can use the tape as
rewritable working memory.

EGPT's computation model is different:

1. **The tape is read-only.** A `ComputerProgram` is a `List Bool` — a sequence
   of binary instructions generated by an `IIDParticleSource`. Each bit is one
   independent choice from a fair coin (or biased source). The tape records the
   history of a random walk. You read it; you don't rewrite it.

2. **Each bit costs one step.** Reading one `ComputerInstruction` (= `Bool`) from
   the tape is one computational step. The tape is processed sequentially, head
   to tail. There are no jumps, no loops, no revisits.

3. **The tape IS maximally compressed.** For a `ParticlePath`, every bit is `true`
   (`PathCompress_AllTrue`). There is zero redundancy. Every bit carries
   information. This is Shannon's optimal code for an IID source — and
   `IIDParticleSource` IS Shannon's source.

4. **Therefore: time complexity = tape length = information content.** The LFTA
   proves primes are perfect Shannon coders (`log(n) = Σ v_p(n) · log(p)`).
   Rota's theorem proves log is the unique entropy function. RECT/IRECT proves
   information content = program complexity. Sequential reading proves
   program complexity = time complexity. The chain is closed.

## The Read Head Model

We formalize this as a `ReadHead` that processes a tape bit by bit. At each
step, the head reads one bit and advances. The number of steps taken is
provably equal to the tape length. No loops, no revisits, no free jumps.

This is intentionally minimal: the "computation" IS the reading. The tape
(generated by the IID source, compressed into a ParticlePath, encoding the
CNF's constraint structure) already contains the answer. The read head's job
is to process it, and the cost of processing is the tape length.
-/

/--
The state of a sequential tape reader at any point during execution.
`remaining` is the unread portion of the tape; `steps` counts how many
bits have been read so far.
-/
structure ReadHead where
  remaining : ComputerTape
  steps     : ℕ

/--
Initialize the read head at the beginning of a tape. Zero steps taken.
-/
def ReadHead.init (tape : ComputerTape) : ReadHead :=
  { remaining := tape, steps := 0 }

/--
One step of execution: read one bit from the tape head, advance, increment
the step counter. Returns `none` if the tape is exhausted.
-/
def ReadHead.step (head : ReadHead) : Option (Bool × ReadHead) :=
  match head.remaining with
  | [] => none
  | bit :: rest => some (bit, { remaining := rest, steps := head.steps + 1 })

/--
Run the read head to completion: process every bit on the tape sequentially.
Returns the final state (empty tape, all steps counted).
-/
def ReadHead.run : ReadHead → ReadHead
  | { remaining := [], steps := s } => { remaining := [], steps := s }
  | { remaining := _ :: rest, steps := s } =>
      ReadHead.run { remaining := rest, steps := s + 1 }
termination_by head => head.remaining.length

/--
**The time complexity of a program in the EGPT model**: the number of
sequential read steps required to process the entire tape.

This is defined as the step count after running the read head to completion.
-/
def timeComplexity (prog : ComputerProgram) : ℕ :=
  (ReadHead.init prog |>.run).steps

/-!
### Core Theorems: Time Complexity = Tape Length
-/

/--
After running the read head on a tape, the remaining tape is empty.
Every bit has been processed.
-/
theorem ReadHead.run_exhausts (head : ReadHead) :
    (head.run).remaining = [] := by
  induction head using ReadHead.run.induct with
  | case1 s => simp [ReadHead.run]
  | case2 bit rest s ih => simp [ReadHead.run]; exact ih

/--
The step count after running equals the initial steps plus the tape length.
This is the key lemma: every bit contributes exactly one step.
-/
theorem ReadHead.run_steps (head : ReadHead) :
    (head.run).steps = head.steps + head.remaining.length := by
  induction head using ReadHead.run.induct with
  | case1 s => simp [ReadHead.run]
  | case2 bit rest s ih =>
    simp [ReadHead.run]
    rw [ih]
    simp [List.length_cons]
    omega

/--
**Time complexity equals tape length.**

For any `ComputerProgram`, the EGPT time complexity (number of sequential
read operations) is exactly the tape length. Each bit costs one step.
No free memory access. No loops. No revisits.

This is the formal statement that in the EGPT computation model,
**program complexity = time complexity = information content**.

Combined with:
- RECT/IRECT: information content = program complexity
- Shannon SCT: optimal code length = entropy for IID source
- Rota: log is the unique entropy function
- LFTA: primes are perfect Shannon coders

The chain is: time complexity = tape length = information content = entropy.
-/
theorem timeComplexity_eq_length (prog : ComputerProgram) :
    timeComplexity prog = prog.length := by
  simp [timeComplexity, ReadHead.init, ReadHead.run_steps]

/--
Time complexity of a `ParticlePath` program equals its `toNat` value.
Since `toNat p = p.val.length`, this connects the time complexity to the
natural number the path represents.
-/
theorem timeComplexity_eq_toNat (p : ParticlePath) :
    timeComplexity p.val = toNat p := by
  rw [timeComplexity_eq_length]
  rfl

/--
Time complexity is additive under program composition.
Concatenating two programs costs the sum of their individual costs.
This reflects that sequential reading of `p ++ q` reads `p` then `q`.
-/
theorem timeComplexity_append (p q : ComputerProgram) :
    timeComplexity (List.append p q) = timeComplexity p + timeComplexity q := by
  simp [timeComplexity_eq_length]

/--
Time complexity of the empty program is zero.
-/
@[simp] theorem timeComplexity_nil : timeComplexity ([] : ComputerProgram) = 0 := by
  simp [timeComplexity_eq_length]

/--
Time complexity of a single instruction is one.
-/
@[simp] theorem timeComplexity_singleton (b : Bool) :
    timeComplexity [b] = 1 := by
  simp [timeComplexity_eq_length]

/-!
### Connection to RECT/IRECT: Time = Information

The EGPT equivalence cycle closes here. We show that time complexity
(sequential read steps) coincides with information content (IRECT) and
program complexity (RECT). The three quantities are the same number.
-/

/--
**The EGPT Equivalence: Time = Information = Program Complexity.**

For any `ComputationalDescription` (= `PathProgram`), the time complexity
of its tape equals its program complexity, which equals its information
content (by IRECT). All three are the same natural number.
-/
theorem time_eq_information_eq_complexity (prog : ComputationalDescription) :
    timeComplexity prog.tape = prog.complexity ∧
    (prog.complexity : ℝ) = IRECT_Program_to_Entropy prog := by
  constructor
  · simp [timeComplexity_eq_length, PathProgram.complexity]
  · simp [IRECT_Program_to_Entropy, PathProgram.complexity]

/--
**Corollary: For any information content L, the program that realizes it
has time complexity L.** There is no gap between information and time.
-/
theorem time_complexity_of_rect_program (L : ℕ) :
    ∃ (prog : ComputationalDescription),
      timeComplexity prog.tape = L ∧
      prog.complexity = L ∧
      IRECT_Program_to_Entropy prog = (L : ℝ) := by
  rcases IRECT_RECT_inverse_for_integer_complexity L with ⟨prog, h_entropy, h_complexity⟩
  exact ⟨prog, by rw [timeComplexity_eq_length, ← h_complexity]; rfl,
         h_complexity, h_entropy⟩

/-!
### Why O(1) Memory Access Is Wrong

In the standard RAM model, accessing memory cell n costs O(1) regardless of n.
This means a program of length L can "jump" to any of 2^L addressable cells
for free, enabling unbounded computation per bit of input.

In the EGPT model, there are no jumps. The tape is read sequentially. To
access the n-th bit, you must read bits 1 through n. The cost of reaching
position n is n, not 1.

This is not an arbitrary choice — it follows from the physical model:
- The tape is a particle path (a random walk history)
- Each bit is one step of the walk
- You cannot "skip ahead" in a walk — each step depends on the previous position
- The walk IS the computation, and each step costs one unit of time

The consequence: a program of length L processes exactly L bits of information
in exactly L time steps. There is no mechanism to amplify L bits into 2^L
steps of work, because there are no loops or revisits.
-/

end EGPT.Complexity.UTM

-- EGPT — Electronic Graph Paper Theory
-- Copyright (C) 2026 Essam Abadir
-- Licensed under the DeSciX Community Source Code License (DCSL) v1.0.
-- See LICENSE and DeSciX_Community_License_v1.pdf in the repository root.
-- Provided WITHOUT ANY WARRANTY. See the DCSL for details.
